version: 1.2
workflows:
  - subclass: WDL
    name: AnnotateAF
    primaryDescriptorPath: /wdl/AnnotateAF.wdl
    filters:
      branches:
        - main
        - kj_project_gnomad_lr
      tags:
        - /.*/

  - subclass: WDL
    name: QcAnnotations
    primaryDescriptorPath: /wdl/QcAnnotations.wdl
    filters:
      branches:
        - main
        - kj_project_gnomad_lr
      tags:
        - /.*/
