"""Static HTML report and manifest helpers for ploidy plots."""

from __future__ import annotations

from dataclasses import dataclass, fields
from html import escape
import logging
import os
from pathlib import Path
import shutil
from typing import Iterable, Optional

import numpy as np
import pandas as pd


logger = logging.getLogger(__name__)

_FIGURE_SUFFIXES = {".png", ".jpg", ".jpeg", ".svg", ".pdf"}
_TABLE_SUFFIXES = {".tsv", ".txt", ".csv"}
_SKIP_TOP_LEVEL_DIRS = {"figures", "report", "tables"}


@dataclass(frozen=True)
class PlotArtifact:
    """Metadata for one plot or table artifact."""

    artifact_id: str
    category: str
    kind: str
    title: str
    caption: str
    source_path: str
    report_path: str
    sample: str
    chromosome: str
    format: str
    size_bytes: int


def write_plot_report(
    output_dir: str,
    *,
    chrom_df: Optional[pd.DataFrame] = None,
    bin_df: Optional[pd.DataFrame] = None,
    sex_df: Optional[pd.DataFrame] = None,
    highlight_sample: str = "",
) -> pd.DataFrame:
    """Write the ploidy plot manifest and static HTML report.

    The report is intentionally dependency-free: generated artifacts remain in
    their original output locations, and ``report/index.html`` links to those
    originals directly.
    """
    root = Path(output_dir)
    root.mkdir(parents=True, exist_ok=True)
    for stale_dir_name in ("figures", "tables"):
        stale_dir = root / stale_dir_name
        if stale_dir.exists():
            shutil.rmtree(stale_dir)

    source_files = _discover_source_artifacts(root)
    artifacts = [_materialize_artifact(root, path) for path in source_files]
    artifacts = [artifact for artifact in artifacts if artifact is not None]

    manifest_df = pd.DataFrame(
        [artifact.__dict__ for artifact in artifacts],
        columns=[field.name for field in fields(PlotArtifact)],
    )
    manifest_path = root / "plot_manifest.tsv"
    manifest_df.to_csv(manifest_path, sep="\t", index=False)

    summary_cards = _build_summary_cards(chrom_df, bin_df, sex_df, manifest_df)
    html = _render_html_report(
        manifest_df,
        summary_cards,
        highlight_sample=highlight_sample,
    )
    report_dir = root / "report"
    report_dir.mkdir(exist_ok=True)
    (report_dir / "index.html").write_text(html, encoding="utf-8")

    logger.debug("Saved plot manifest: plot_manifest.tsv")
    logger.debug("Saved plot report: report/index.html")
    return manifest_df


def _discover_source_artifacts(root: Path) -> list[Path]:
    """Return plot/table files generated by the plotting command."""
    files: list[Path] = []
    for path in root.rglob("*"):
        if not path.is_file():
            continue
        rel = path.relative_to(root)
        if rel.parts and rel.parts[0] in _SKIP_TOP_LEVEL_DIRS:
            continue
        if path.name == "plot_manifest.tsv":
            continue
        if _is_supported_artifact(path):
            files.append(path)
    return sorted(files, key=lambda p: p.relative_to(root).as_posix())


def _is_supported_artifact(path: Path) -> bool:
    if path.suffix.lower() in _FIGURE_SUFFIXES:
        return True
    if path.name.endswith(".tsv.gz"):
        return True
    return path.suffix.lower() in _TABLE_SUFFIXES


def _materialize_artifact(root: Path, source: Path) -> Optional[PlotArtifact]:
    rel = source.relative_to(root)
    rel_posix = rel.as_posix()
    category = _category_for_path(rel)
    kind = "figure" if source.suffix.lower() in _FIGURE_SUFFIXES else "table"
    report_path = os.path.relpath(source, root / "report")
    title = _title_for_path(rel)
    caption = _caption_for_path(rel, category, kind)
    sample, chromosome = _tags_for_path(rel)
    size_bytes = int(source.stat().st_size)
    artifact_id = _artifact_id(rel)
    format_name = source.suffix.lower().lstrip(".")
    if source.name.endswith(".tsv.gz"):
        format_name = "tsv.gz"

    return PlotArtifact(
        artifact_id=artifact_id,
        category=category,
        kind=kind,
        title=title,
        caption=caption,
        source_path=rel_posix,
        report_path=report_path.replace(os.sep, "/"),
        sample=sample,
        chromosome=chromosome,
        format=format_name,
        size_bytes=size_bytes,
    )


def _artifact_id(rel: Path) -> str:
    stem = rel.as_posix()
    for suffix in (".tsv.gz", ".png", ".pdf", ".svg", ".jpg", ".jpeg", ".tsv", ".txt", ".csv"):
        if stem.endswith(suffix):
            stem = stem[: -len(suffix)]
            break
    return stem.replace("/", "__")


def _category_for_path(rel: Path) -> str:
    parts = rel.parts
    name = rel.name.lower()
    stem = rel.stem.lower()
    parent = parts[0] if parts else ""
    if parent == "ppd" or name.startswith("ppd_"):
        return "ppd"
    if parent == "sample_plots":
        return "per_sample"
    if parent in {"raw_depth_contig", "raw_depth_binned"}:
        return "per_chromosome"
    if name.startswith("site_af_"):
        return "site_af"
    if stem in {"training_loss", "training_loss_gradient"}:
        return "model"
    if any(token in stem for token in ("posterior", "parameter", "factor", "sample_depth", "bin_variance")):
        return "model"
    if name.endswith(".tsv") or name.endswith(".tsv.gz") or name.endswith(".csv") or name.endswith(".txt"):
        return "tables"
    return "overview"


def _title_for_path(rel: Path) -> str:
    if rel.parts and rel.parts[0] == "sample_plots":
        return rel.stem
    name = rel.name
    if name.endswith(".tsv.gz"):
        name = name[:-7]
    else:
        name = rel.stem
    title = name.replace("_", " ").replace("-", " ").strip()
    return title.title() if title else rel.as_posix()


def _caption_for_path(rel: Path, category: str, kind: str) -> str:
    captions = {
        "overview": "Cohort-level ploidy and sex assignment overview.",
        "model": "Model fit and latent-parameter diagnostic artifact.",
        "ppd": "Posterior predictive check diagnostic artifact.",
        "site_af": "Site-level allele-fraction diagnostic artifact.",
        "per_sample": "Per-sample copy-number profile artifact.",
        "per_chromosome": "Per-chromosome bin-level copy-number artifact.",
        "tables": "Tabular plotting diagnostic artifact.",
    }
    if kind == "table":
        return "Tabular data used by the ploidy plotting report."
    return captions.get(category, f"Plot artifact: {rel.as_posix()}")


def _tags_for_path(rel: Path) -> tuple[str, str]:
    sample = ""
    chromosome = ""
    parts = rel.parts
    if parts and parts[0] == "sample_plots":
        sample = rel.stem
    for part in parts:
        if part.startswith("chr"):
            chromosome = part.split("_")[0]
    if not chromosome:
        for token in rel.stem.replace(".", "_").split("_"):
            if token.startswith("chr"):
                chromosome = token
                break
    return sample, chromosome


def _build_summary_cards(
    chrom_df: Optional[pd.DataFrame],
    bin_df: Optional[pd.DataFrame],
    sex_df: Optional[pd.DataFrame],
    manifest_df: pd.DataFrame,
) -> list[tuple[str, str, str]]:
    cards: list[tuple[str, str, str]] = []
    if chrom_df is not None and not chrom_df.empty:
        cards.append(("Samples", _fmt_int(chrom_df["sample"].nunique()), "unique samples"))
        cards.append(("Chromosomes", _fmt_int(chrom_df["chromosome"].nunique()), "reported contigs"))
        if "is_aneuploid" in chrom_df.columns:
            aneuploid_samples = chrom_df.loc[chrom_df["is_aneuploid"], "sample"].nunique()
            cards.append(("Aneuploid Samples", _fmt_int(aneuploid_samples), "with any flagged chromosome"))
    if bin_df is not None and not bin_df.empty:
        cards.append(("Bin Records", _fmt_int(len(bin_df)), "sample-bin observations"))
    if sex_df is not None and not sex_df.empty and "sex" in sex_df.columns:
        sex_counts = sex_df["sex"].astype(str).value_counts().sort_index()
        label = ", ".join(f"{idx}: {_fmt_int(val)}" for idx, val in sex_counts.items())
        cards.append(("Sex Calls", label or "None", "from call table"))
    if not manifest_df.empty:
        cards.append(("Figures", _fmt_int((manifest_df["kind"] == "figure").sum()), "report-linked plots"))
        cards.append(("Tables", _fmt_int((manifest_df["kind"] == "table").sum()), "report-linked tables"))
    return cards


def _render_html_report(
    manifest_df: pd.DataFrame,
    summary_cards: list[tuple[str, str, str]],
    *,
    highlight_sample: str = "",
) -> str:
    sections = [
        ("overview", "Overview"),
        ("model", "Model Diagnostics"),
        ("ppd", "Posterior Predictive Checks"),
        ("site_af", "Site AF Diagnostics"),
        ("per_sample", "Per-Sample Gallery"),
        ("per_chromosome", "Per-Chromosome Gallery"),
        ("tables", "Tables"),
    ]
    cards_html = "".join(
        f"<article class=\"metric\"><span>{escape(title)}</span>"
        f"<strong>{escape(value)}</strong><em>{escape(note)}</em></article>"
        for title, value, note in summary_cards
    )
    section_html = "".join(
        _render_section(manifest_df, category, title)
        for category, title in sections
    )
    highlight_html = (
        f"<p class=\"highlight\">Highlighted sample: <strong>{escape(highlight_sample)}</strong></p>"
        if highlight_sample else ""
    )
    return f"""<!doctype html>
<html lang=\"en\">
<head>
  <meta charset=\"utf-8\">
  <meta name=\"viewport\" content=\"width=device-width, initial-scale=1\">
  <title>GATK-SV Ploidy Report</title>
  <style>
    :root {{ color-scheme: light; --ink: #222832; --muted: #657184; --line: #D8DEE8; --panel: #F7F9FC; --blue: #315F8F; }}
    body {{ margin: 0; font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif; color: var(--ink); background: #fff; }}
    header {{ padding: 32px clamp(20px, 5vw, 72px) 24px; border-bottom: 1px solid var(--line); background: linear-gradient(180deg, #F6F9FC 0%, #FFFFFF 100%); }}
    main {{ padding: 24px clamp(20px, 5vw, 72px) 56px; }}
    h1 {{ margin: 0 0 8px; font-size: clamp(28px, 4vw, 44px); letter-spacing: 0; }}
    h2 {{ margin: 32px 0 14px; font-size: 22px; letter-spacing: 0; }}
    p {{ color: var(--muted); max-width: 920px; line-height: 1.5; }}
    a {{ color: var(--blue); text-decoration: none; }}
    a:hover {{ text-decoration: underline; }}
    .metrics {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin-top: 20px; }}
    .metric {{ border: 1px solid var(--line); border-radius: 8px; padding: 14px 16px; background: #fff; }}
    .metric span {{ display: block; color: var(--muted); font-size: 13px; }}
    .metric strong {{ display: block; margin-top: 5px; font-size: 24px; line-height: 1.15; }}
    .metric em {{ display: block; margin-top: 5px; color: var(--muted); font-size: 12px; font-style: normal; }}
    .gallery {{ display: grid; grid-template-columns: repeat(auto-fit, minmax(280px, 1fr)); gap: 16px; }}
    .artifact {{ border: 1px solid var(--line); border-radius: 8px; overflow: hidden; background: #fff; }}
    .artifact img {{ display: block; width: 100%; height: auto; background: var(--panel); border-bottom: 1px solid var(--line); }}
    .artifact .body {{ padding: 12px 14px 14px; }}
    .artifact h3 {{ margin: 0 0 6px; font-size: 15px; letter-spacing: 0; }}
    .artifact p {{ margin: 0 0 8px; font-size: 13px; }}
    .tagrow {{ color: var(--muted); font-size: 12px; }}
    .empty {{ border: 1px dashed var(--line); border-radius: 8px; padding: 16px; background: var(--panel); }}
    .table-list {{ columns: 2 320px; padding-left: 18px; }}
    .highlight {{ margin-top: 0; }}
  </style>
</head>
<body>
  <header>
    <h1>GATK-SV Ploidy Report</h1>
        <p>Static report generated from the ploidy plotting outputs. Links in this report point directly to the original artifacts, with the full manifest in <a href="../plot_manifest.tsv">plot_manifest.tsv</a>.</p>
    {highlight_html}
    <section class=\"metrics\">{cards_html}</section>
  </header>
  <main>
    {section_html}
  </main>
</body>
</html>
"""


def _render_section(manifest_df: pd.DataFrame, category: str, title: str) -> str:
    if manifest_df.empty:
        rows = manifest_df
    else:
        rows = manifest_df[manifest_df["category"] == category].copy()
    if rows.empty:
        return f"<section><h2>{escape(title)}</h2><div class=\"empty\">No artifacts were generated for this section.</div></section>"
    if category == "tables":
        items = "".join(
            f"<li><a href=\"{escape(row.report_path)}\">{escape(row.title)}</a> <span class=\"tagrow\">({escape(row.format)})</span></li>"
            for row in rows.itertuples(index=False)
        )
        return f"<section><h2>{escape(title)}</h2><ul class=\"table-list\">{items}</ul></section>"
    cards = "".join(_render_artifact_card(row) for row in rows.itertuples(index=False))
    return f"<section><h2>{escape(title)}</h2><div class=\"gallery\">{cards}</div></section>"


def _render_artifact_card(row) -> str:
    link = escape(row.report_path)
    if row.format in {"png", "jpg", "jpeg", "svg"}:
        media = f"<a href=\"{link}\"><img src=\"{link}\" loading=\"lazy\" alt=\"{escape(row.title)}\"></a>"
    else:
        media = f"<div class=\"empty\"><a href=\"{link}\">Open {escape(row.format.upper())}</a></div>"
    tags = [tag for tag in (row.sample, row.chromosome, row.source_path) if tag]
    tag_text = " | ".join(tags)
    return (
        f"<article class=\"artifact\">{media}<div class=\"body\">"
        f"<h3><a href=\"{link}\">{escape(row.title)}</a></h3>"
        f"<p>{escape(row.caption)}</p>"
        f"<div class=\"tagrow\">{escape(tag_text)}</div>"
        f"</div></article>"
    )


def _fmt_int(value: int | np.integer) -> str:
    return f"{int(value):,}"


def read_manifest(path: str | Path) -> pd.DataFrame:
    """Read a plot manifest written by :func:`write_plot_report`."""
    return pd.read_csv(path, sep="\t")


def iter_category(manifest_df: pd.DataFrame, category: str) -> Iterable[pd.Series]:
    """Yield manifest rows for a category in report order."""
    for _, row in manifest_df[manifest_df["category"] == category].iterrows():
        yield row
