#!/usr/bin/env python

# Input constants
TSV_DELIMITER = '\t'
METRIC_FILE_NAME_COLUMN = "METRIC"
METRIC_FILE_VALUE_COLUMN = "VALUE"
CRITERIA_METRIC_COLUMN = "METRIC"
CRITERIA_MIN_COLUMN = "MIN"
CRITERIA_MAX_COLUMN = "MAX"
PASS_STRING = "PASS"
FAIL_STRING = "FAIL"
NA_STRING = "NA"
