name: Test WDLs

on:
  push:
    branches:
      - main
    paths:
      - 'wdl/**'
      - 'inputs/**'
      - 'scripts/inputs/build_default_inputs.sh'
      - 'scripts/test/terra_validation.py'
      - 'scripts/test/miniwdl_validation.py'
      - 'scripts/test/validate.sh'
  pull_request:
    branches:
      - main
    paths:
      - 'wdl/**'
      - 'inputs/**'
      - 'scripts/inputs/build_default_inputs.sh'
      - 'scripts/test/terra_validation.py'
      - 'scripts/test/miniwdl_validation.py'
      - 'scripts/test/validate.sh'

jobs:
  syntax_test_job:
    runs-on: ubuntu-24.04
    name: Check WDL Syntax
    strategy:
      matrix:
        python-version: ['3.8']
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Setup Java
        uses: actions/setup-java@v3
        with:
          # See https://github.com/actions/setup-java for the available options.
          distribution: 'temurin'
          java-version: '17'

      - name: Setup
        run: |
          python -m pip install --upgrade pip
          # Setup for running miniwdl
          pip install miniwdl
          
          # Setup for running womtool
          pip install jinja2==3.1.2
          wget -O womtool.jar https://github.com/broadinstitute/cromwell/releases/download/84/womtool-84.jar
          scripts/inputs/build_default_inputs.sh -d .

      - name: Test with Miniwdl
        run: |
          python scripts/test/miniwdl_validation.py \
            --imports-dir wdl \
            wdl/*.wdl

      - name: Test with WOMtool
        run: |
          scripts/test/validate.sh -t -d . -j womtool.jar
